"""
Deprecated legacy pipeline entrypoint.

This module is kept for compatibility and historical reference only.
Current production pipeline entrypoint: `app.main_summary_v2`
Current API service entrypoint: `backend.app.main`

Do not add new product logic here unless you are intentionally maintaining the
legacy path.
"""

import json
from datetime import datetime
from pathlib import Path

from config import BASE_DIR, settings
from intelligence.llm_executor import execute_routed_task
from models import Insight, Signal
from storage.s3_writer import S3Writer


OUTPUT_DIR = BASE_DIR / "output"
CONTEXT_FILE = BASE_DIR / "app" / "context" / "personal_context.json"
SIGNALS_FILE = OUTPUT_DIR / "signals.json"


def ensure_output_dir() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def load_personal_context() -> dict:
    if not CONTEXT_FILE.exists():
        return {
            "background": "",
            "projects": [],
            "technical_focus": [],
            "interests": [],
            "thinking_style": "",
            "writing_style": "",
            "career_direction": "",
        }

    with open(CONTEXT_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def collect_sample_signals() -> list[Signal]:
    now = datetime.now(settings.timezone).isoformat()

    signals = [
        Signal(
            title="AI agents are shifting from demo workflows to production operations",
            summary=(
                "More teams are moving agent systems from experimental prototypes "
                "into operational pipelines with stronger observability, guardrails, "
                "and workflow orchestration."
            ),
            url="https://example.com/ai-agents-production",
            author="Sample Source",
            source="sample",
            category="AI Agent",
            published_at=now,
            collected_at=now,
        ),
        Signal(
            title="Context engineering is becoming as important as prompt engineering",
            summary=(
                "Stable context pipelines, structured memory, and reliable retrieval "
                "are increasingly seen as critical for production AI systems."
            ),
            url="https://example.com/context-engineering",
            author="Sample Source",
            source="sample",
            category="AI Architect",
            published_at=now,
            collected_at=now,
        ),
    ]

    return signals[: settings.max_signals_per_run]


def load_signals_from_file() -> list[Signal]:
    """
    Load signals from output/signals.json generated by collectors.
    Supports two formats:
    1. list[dict]
    2. {"generated_at": ..., "signals": [...]}
    """
    if not SIGNALS_FILE.exists():
        print(f"Signals file not found: {SIGNALS_FILE}")
        return []

    try:
        with open(SIGNALS_FILE, "r", encoding="utf-8") as f:
            raw_data = json.load(f)
    except Exception as e:
        print(f"Failed to read signals file: {e}")
        return []

    if isinstance(raw_data, dict) and "signals" in raw_data:
        raw_signals = raw_data.get("signals", [])
    elif isinstance(raw_data, list):
        raw_signals = raw_data
    else:
        print("Signals file format not recognized.")
        return []

    signals: list[Signal] = []

    for idx, item in enumerate(raw_signals, start=1):
        try:
            # ✅ 新逻辑：summary优先
            raw_summary = (item.get("summary") or "").strip()
            raw_content = (item.get("content") or "").strip()

            summary = raw_summary if raw_summary else raw_content

            author = item.get("author", "Unknown")
            source = item.get("source", "external")
            url = item.get("url", "")

            published_at = (
                item.get("published_at")
                or item.get("timestamp")
                or datetime.now(settings.timezone).isoformat()
            )

            collected_at = item.get("collected_at") or datetime.now(settings.timezone).isoformat()

            title = item.get("title")

            if not title:
                fallback_text = summary or raw_content
                if fallback_text:
                    title = fallback_text[:120].replace("\n", " ").strip()
                else:
                    title = f"Signal {idx}"

            category = item.get("category", source)

            signals.append(
                Signal(
                    title=title,
                    summary=summary,
                    url=url,
                    author=author,
                    source=source,
                    category=category,
                    published_at=published_at,
                    collected_at=collected_at,
                )
            )

        except Exception as e:
            print(f"Failed to parse signal #{idx}: {e}")

    return signals[: settings.max_signals_per_run]


def collect_signals() -> list[Signal]:
    file_signals = load_signals_from_file()

    if file_signals:
        print(f"Loaded {len(file_signals)} signals from file.")
        return file_signals

    print("No collected signals found. Falling back to sample signals.")
    return collect_sample_signals()


def generate_insight(signal: Signal, personal_context: dict) -> Insight:
    prompt = f"""
You are generating a personalized AI Radar insight.

User context:
{json.dumps(personal_context, ensure_ascii=False, indent=2)}

Signal:
{json.dumps(signal.to_dict(), ensure_ascii=False, indent=2)}

Return a concise personalized analysis in JSON with exactly these keys:
why_it_matters
relevance_to_projects
relevance_to_career
synthesized_insight
"""

    result = execute_routed_task(
        task_type="structure",
        temperature=0.7,
        messages=[
            {
                "role": "system",
                "content": (
                    "You are an AI Radar insight engine focused on personalized, "
                    "practical, high-signal analysis."
                ),
            },
            {
                "role": "user",
                "content": prompt,
            },
        ],
        json_mode=True,
    )

    parsed = result.parsed_json or json.loads(result.raw_text or "{}")

    return Insight(
        signal_title=signal.title,
        signal_summary=signal.summary,
        why_it_matters=parsed.get("why_it_matters", ""),
        relevance_to_projects=parsed.get("relevance_to_projects", ""),
        relevance_to_career=parsed.get("relevance_to_career", ""),
        synthesized_insight=parsed.get("synthesized_insight", ""),
    )


def save_json(data: dict | list, file_path: Path) -> None:
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def upload_outputs_to_s3(
    s3: S3Writer,
    today: str,
    signals_data: list[dict],
    insights_data: list[dict],
    daily_radar: dict,
) -> None:
    dated_signals_key = f"signals/{today}/signals.json"
    dated_insights_key = f"insights/{today}/insights.json"
    dated_daily_key = f"daily/{today}/daily_radar.json"

    latest_signals_key = "signals/latest/signals.json"
    latest_insights_key = "insights/latest/insights.json"
    latest_daily_key = "daily/latest/daily_radar.json"

    s3.upload_json(signals_data, dated_signals_key)
    s3.upload_json(insights_data, dated_insights_key)
    s3.upload_json(daily_radar, dated_daily_key)

    s3.upload_json(signals_data, latest_signals_key)
    s3.upload_json(insights_data, latest_insights_key)
    s3.upload_json(daily_radar, latest_daily_key)

    print(f"Uploaded signals to S3: {dated_signals_key}")
    print(f"Uploaded insights to S3: {dated_insights_key}")
    print(f"Uploaded daily radar to S3: {dated_daily_key}")
    print(f"Uploaded latest signals to S3: {latest_signals_key}")
    print(f"Uploaded latest insights to S3: {latest_insights_key}")
    print(f"Uploaded latest daily radar to S3: {latest_daily_key}")


def main() -> None:
    settings.validate()
    ensure_output_dir()

    now = datetime.now(settings.timezone)
    today = now.strftime("%Y-%m-%d")

    print("Starting AI Radar run...")
    print(f"Timezone: {settings.radar_timezone}")
    print(f"Generated at: {now.isoformat()}")
    print(f"Run date: {today}")

    personal_context = load_personal_context()
    print("Personal context loaded.")

    signals = collect_signals()
    print(f"Collected {len(signals)} signals.")

    insights: list[Insight] = []

    for idx, signal in enumerate(signals, start=1):
        print(f"Generating insight {idx}/{len(signals)} for signal: {signal.title}")
        insight = generate_insight(signal, personal_context)
        insights.append(insight)

    signals_data = [s.to_dict() for s in signals]
    insights_data = [i.to_dict() for i in insights]

    daily_radar = {
        "date": today,
        "timezone": settings.radar_timezone,
        "generated_at": now.isoformat(),
        "signal_count": len(signals_data),
        "insight_count": len(insights_data),
        "signals": signals_data,
        "insights": insights_data,
    }

    save_json(signals_data, OUTPUT_DIR / "signals.json")
    save_json(insights_data, OUTPUT_DIR / "insights.json")
    save_json(daily_radar, OUTPUT_DIR / "daily_radar.json")

    print("Saved all outputs locally.")

    s3 = S3Writer()
    upload_outputs_to_s3(
        s3=s3,
        today=today,
        signals_data=signals_data,
        insights_data=insights_data,
        daily_radar=daily_radar,
    )

    print("AI Radar run completed successfully.")


if __name__ == "__main__":
    main()
