from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


def _safe_name(text: str) -> str:
    text = (text or "").strip()
    text = re.sub(r"[\\/:*?\"<>|]", "", text)
    text = re.sub(r"\s+", "_", text)
    return text[:120] if text else "Untitled"


def _ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _wiki_link(note_name: str) -> str:
    return f"[[{note_name}]]"

def _display_title(text: str) -> str:
    text = (text or "").strip()
    if not text:
        return "Untitled Signal"
    return re.sub(r"\s+", " ", text)


def _signal_sort_key(signal: dict[str, Any]) -> tuple[float, float]:
    project_links = signal.get("project_links", []) or []
    project_score = 0.0
    if project_links and isinstance(project_links, list):
        project_score = max(float(item.get("score", 0) or 0) for item in project_links if isinstance(item, dict))

    signal_score = float(signal.get("score", 0) or 0)
    return (project_score, signal_score)

def _signal_wiki_link(signal: dict[str, Any]) -> str:
    raw_title = signal.get("title", "Untitled Signal")
    file_name = _safe_name(raw_title)
    display_name = _display_title(raw_title)
    return f"[[{file_name}|{display_name}]]"

def _topic_note_name(topic: str) -> str:
    return _safe_name(topic or "General AI")


def _collect_topic_groups(signals_data: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    topic_map: dict[str, list[dict[str, Any]]] = {}

    for signal in signals_data:
        topic = (signal.get("topic") or "General AI").strip()
        topic_map.setdefault(topic, []).append(signal)

    return topic_map

def _render_topic_note(topic: str, topic_signals: list[dict[str, Any]]) -> str:
    sorted_signals = sorted(
        topic_signals,
        key=lambda s: float(s.get("score", 0) or 0),
        reverse=True,
    )

    top_signals = sorted_signals[:8]

    related_projects = []
    seen_projects = set()

    for signal in sorted_signals:
        for pid in signal.get("projects", []) or []:
            if pid and pid not in seen_projects:
                seen_projects.add(pid)
                related_projects.append(pid)

    project_lines = []
    for pid in related_projects:
        project_lines.append(f"- {_wiki_link(_project_id_to_note_name(pid))}")

    if not project_lines:
        project_lines = ["- None"]

    top_signal_lines = [f"- {_signal_wiki_link(signal)}" for signal in top_signals] if top_signals else ["- None"]
    all_signal_lines = [f"- {_signal_wiki_link(signal)}" for signal in sorted_signals[:20]] if sorted_signals else ["- None"]

    return f"""# {topic}

## Signal Count
{len(topic_signals)}

## Related Projects
{chr(10).join(project_lines)}

## Top Signals
{chr(10).join(top_signal_lines)}

## Topic Signals
{chr(10).join(all_signal_lines)}

## Notes
Generated by AI Radar topic intelligence exporter.
"""

def _export_topic_notes(vault_root: Path, signals_data: list[dict[str, Any]]) -> None:
    topic_dir = vault_root / "03_Research" / "AI_Trend_Topics"
    _ensure_dir(topic_dir)

    topic_groups = _collect_topic_groups(signals_data)

    exported_count = 0

    for topic, topic_signals in topic_groups.items():
        if not topic_signals:
            continue

    # Export even a single item so the layer remains testable end to end.
        if len(topic_signals) < 1:
            continue

        note_name = _topic_note_name(topic)
        note_path = topic_dir / f"{note_name}.md"
        note_path.write_text(_render_topic_note(topic, topic_signals), encoding="utf-8")
        exported_count += 1

    print(f"[INFO] Exported {exported_count} topic notes.")

def _project_id_to_note_name(project_id: str) -> str:
    mapping = {
        "ai_radar": "AI_Radar",
        "glap": "GLAP",
        "ai_cognitive": "AI_Cognitive_OS",
        "trajectory_memory": "Trajectory_Memory",
    }
    return mapping.get(project_id, project_id)


def _render_signal_note(signal: dict[str, Any]) -> str:
    title = signal.get("title", "Untitled Signal")
    summary = signal.get("summary", "")
    why_it_matters = signal.get("why_it_matters", "")
    relevance_to_projects = signal.get("relevance_to_projects", "")
    relevance_to_career = signal.get("relevance_to_career", "")
    synthesized_insight = signal.get("synthesized_insight", "")
    topic = signal.get("topic", "General AI")
    source = signal.get("source", "")
    url = signal.get("url", "")
    published_at = signal.get("published_at", "")
    collected_at = signal.get("collected_at", "")
    score = signal.get("score", "")
    projects = signal.get("projects", [])

    related_project_links = []
    for pid in projects:
        related_project_links.append(f"- {_wiki_link(_project_id_to_note_name(pid))}")

    if not related_project_links:
        related_project_links = ["- None"]

    return f"""# {title}

## Summary
{summary}

## Why it matters
{why_it_matters}

## Relevance to projects
{relevance_to_projects}

## Relevance to career
{relevance_to_career}

## Synthesized insight
{synthesized_insight}

## Topic
{_wiki_link(topic)}

## Related Projects
{chr(10).join(related_project_links)}

## Metadata
- Source: {source}
- URL: {url}
- Published At: {published_at}
- Collected At: {collected_at}
- Score: {score}
"""


def _render_daily_radar_note(daily_radar: dict[str, Any]) -> str:
    date = daily_radar.get("date", "")
    executive_summary = daily_radar.get("executive_summary", "")
    rising_topics = daily_radar.get("rising_topics", [])
    strategic_priority = daily_radar.get("strategic_priority", [])
    signals = daily_radar.get("signals", [])
    agent_watch = daily_radar.get("agent_watch", {}) if isinstance(daily_radar.get("agent_watch"), dict) else {}

    top_signal_links = []
    for signal in signals[:10]:
        top_signal_links.append(f"- {_signal_wiki_link(signal)}")

    if not top_signal_links:
        top_signal_links = ["- None"]

    rising_topic_lines = []
    if isinstance(rising_topics, list):
        for topic in rising_topics[:10]:
            if isinstance(topic, dict):
                topic_name = topic.get("topic", "Unknown Topic")
                rising_topic_lines.append(f"- {_wiki_link(topic_name)}")
            else:
                rising_topic_lines.append(f"- {topic}")

    if not rising_topic_lines:
        rising_topic_lines = ["- None"]

    strategic_lines = []
    if isinstance(strategic_priority, list):
        for item in strategic_priority[:10]:
            if isinstance(item, dict):
                topic_name = item.get("topic", "Unknown Topic")
                strategic_lines.append(f"- {_wiki_link(topic_name)}")
            else:
                strategic_lines.append(f"- {item}")

    if not strategic_lines:
        strategic_lines = ["- None"]

    agent_watch_lines = []
    highlights = agent_watch.get("highlights", []) if isinstance(agent_watch.get("highlights"), list) else []
    for item in highlights[:3]:
        if not isinstance(item, dict):
            continue
        title = item.get("title", "Untitled Agent Signal")
        summary = item.get("summary", "")
        stars = item.get("repo_stars")
        source = item.get("source", "")
        details = []
        if stars is not None:
            details.append(f"{stars} stars")
        if source:
            details.append(str(source))
        detail_suffix = f" ({', '.join(details)})" if details else ""
        agent_watch_lines.append(f"- **{title}**{detail_suffix}: {summary}")

    if not agent_watch_lines:
        agent_watch_lines = ["- None"]

    return f"""# Daily Radar - {date}

## Executive Summary
{executive_summary}

## Top Signals
{chr(10).join(top_signal_links)}

## Rising Topics
{chr(10).join(rising_topic_lines)}

## Strategic Priority
{chr(10).join(strategic_lines)}

## AI Agent Watch
{chr(10).join(agent_watch_lines)}
"""


def _replace_section(content: str, section_title: str, new_body: str) -> str:
    pattern = rf"(## {re.escape(section_title)}\n)(.*?)(?=\n## |\Z)"
    replacement = rf"\1{new_body.strip()}\n"
    if re.search(pattern, content, flags=re.DOTALL):
        return re.sub(pattern, replacement, content, flags=re.DOTALL)

    if content.strip():
        return content.rstrip() + f"\n\n## {section_title}\n{new_body.strip()}\n"
    return f"## {section_title}\n{new_body.strip()}\n"


def _update_project_note(project_file: Path, project: dict[str, Any], linked_signals: list[dict[str, Any]]) -> None:
    project_name = project.get("name", project_file.stem)
    status = project.get("status", "")
    description = project.get("description", "")
    topics = project.get("topics", [])

    topic_links = "\n".join([f"- {_wiki_link(t)}" for t in topics]) if topics else "- None"

    sorted_signals = sorted(
        linked_signals,
        key=_signal_sort_key,
        reverse=True,
    )

    high_relevance = []
    medium_relevance = []

    for signal in sorted_signals:
        project_links = signal.get("project_links", []) or []
        project_score = 0.0
        if project_links and isinstance(project_links, list):
            project_score = max(
                float(item.get("score", 0) or 0)
                for item in project_links
                if isinstance(item, dict)
            )

        if project_score >= 6:
            high_relevance.append(signal)
        else:
            medium_relevance.append(signal)

    high_relevance = high_relevance[:6]
    medium_relevance = medium_relevance[:6]

    if high_relevance:
        high_lines = "\n".join([f"- {_signal_wiki_link(item)}" for item in high_relevance])
    else:
        high_lines = "- None"

    if medium_relevance:
        medium_lines = "\n".join([f"- {_signal_wiki_link(item)}" for item in medium_relevance])
    else:
        medium_lines = "- None"

    recent_signals_body = f"""### High Relevance Signals
{high_lines}

### Medium Relevance Signals
{medium_lines}"""

    if project_file.exists():
        content = project_file.read_text(encoding="utf-8")
    else:
        content = f"# {project_name}\n"

    content = _replace_section(content, "Status", status or "unknown")
    content = _replace_section(content, "Description", description or "")
    content = _replace_section(content, "Topics", topic_links)
    content = _replace_section(content, "Recent Signals", recent_signals_body)

    project_file.write_text(content, encoding="utf-8")


def export_to_obsidian(
    vault_root: str | Path,
    signals_data: list[dict[str, Any]],
    daily_radar: dict[str, Any],
    project_registry_path: str | Path,
) -> None:
    vault_root = Path(vault_root)

    radar_signals_dir = vault_root / "04_Insights" / "Radar_Signals"
    radar_daily_dir = vault_root / "06_Daily" / "Radar"
    projects_dir = vault_root / "01_Projects"

    _ensure_dir(radar_signals_dir)
    _ensure_dir(radar_daily_dir)
    _ensure_dir(projects_dir)

    # 1. Export signal notes
    exported_signal_map: dict[str, dict[str, Any]] = {}

    for signal in signals_data:
        if not signal.get("projects"):
            continue

        if not any([
            (signal.get("why_it_matters") or "").strip(),
            (signal.get("relevance_to_projects") or "").strip(),
            (signal.get("relevance_to_career") or "").strip(),
            (signal.get("synthesized_insight") or "").strip(),
        ]):
            continue

        note_name = _safe_name(signal.get("title", "Untitled Signal"))
        note_path = radar_signals_dir / f"{note_name}.md"
        note_path.write_text(_render_signal_note(signal), encoding="utf-8")
        exported_signal_map[note_name] = signal

    # 2. Export daily radar note
    date_str = daily_radar.get("date", "unknown-date")
    daily_note_name = f"{date_str}_AI_Radar"
    daily_note_path = radar_daily_dir / f"{daily_note_name}.md"
    daily_note_path.write_text(_render_daily_radar_note(daily_radar), encoding="utf-8")

    # 3. Update project notes
    project_registry_path = Path(project_registry_path)
    if not project_registry_path.exists():
        print(f"[WARN] project registry not found: {project_registry_path}")
        return

    registry = json.loads(project_registry_path.read_text(encoding="utf-8"))
    projects = registry.get("projects", [])

    for project in projects:
        project_id = project.get("project_id", "")
        note_name = _project_id_to_note_name(project_id)
        project_file = projects_dir / f"{note_name}.md"

        linked_signals = [
            signal for signal in signals_data
            if project_id in (signal.get("projects") or [])
        ]

        _update_project_note(project_file, project, linked_signals)

    # 4. Export topic notes
    _export_topic_notes(vault_root, signals_data)

    print(f"[INFO] Exported {len(exported_signal_map)} signal notes to Obsidian.")
    print(f"[INFO] Exported daily radar note: {daily_note_path.name}")
    print("[INFO] Project notes updated.")
